### ISSUE TITLE
Sync of repo after LOS FOD revert fails build

### ISSUE THREAD

**Issue by campbellhennessy** [AndyCGYan/treble_build_los#10]
Hello,

I am new to building android so maybe I missed something obvious.  But just wanted to report this in case others run into the same issue.

My first attempts to build with this build script failed on errors stemming from missing FOD externals.  On later attempts I interrupted the script at a couple of points and noticed that while the LOS FOD revert patch worked, somewhere (and I never traced where) in the other patch routines the repo was resyncing and overwriting the revert.  I managed to build successfully by moving the LOS FOD revert section of the script to the bottom of the patch section.  I am not sure if changing the order has any side effects but I have not noticed any so far.

All the best!

**Comment by AndyCGYan** [comment]
> somewhere (and I never traced where) in the other patch routines the repo was resyncing and overwriting the revert
https://github.com/AndyCGYan/treble_experimentations/commit/a4664343d3730a4e58dea248541eaed34b9f3f06 deals with just that.
The revert has to come before patching - the fingerprint patches rely on clean (no FOD) code.

**Comment by campbellhennessy** [comment]
I found my error.  I didn't read the build script fully and thought it was pointing to ../treble_experimentations for the apply_patch script.  However it points to the home directory... and my build user has PHH's original treble_experimentations in the home directory so that was running and resyncing.  Closing issue.  Thanks for pointing me in the right direction
