### ISSUE TITLE
Patch failed at 0001 Squashed revert of LOS FOD implementation

### ISSUE THREAD

**Issue by robpower** [AndyCGYan/treble_build_los#3]
### Issue: 
Build not successful due to failure while apply PHH patches.

### Steps to reproduce:
Follow the instructions on Readme.md, setup environment and build using buildbot_treble.sh.

### Detailed Description:
Running buildbot_treble.sh fail to build successfully. Error can be traced back to command on line 28 https://github.com/AndyCGYan/treble_build_los/blob/cdc219defb41883b01e4ef13851f8285429cafed/buildbot_treble.sh#L28
which fails with the following error (without stopping the process):

> Applying: Squashed revert of LOS FOD implementation
> error: patch failed: packages/SystemUI/src/com/android/systemui/biometrics/FODCircleView.java:1
> error: packages/SystemUI/src/com/android/systemui/biometrics/FODCircleView.java: patch does not apply
Patch failed at 0001 Squashed revert of LOS FOD implementation
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort"

Process do continue,  showing additional errors like: 

> error: frameworks/base/: prior sync failed; rebase still in progress
error: Cannot checkout LineageOS/android_frameworks_base

and finally fails

> system/bt/stack/btm/btm_acl.cc:1211:6: error: function-like macro 'BtmBypassExtraAclSetup' is not defined
#if (BTM_BYPASS_EXTRA_ACL_SETUP == FALSE)
>    ^
device/phh/treble/bluetooth/bdroid_buildcfg.h:52:36: note: expanded from macro 'BTM_BYPASS_EXTRA_ACL_SETUP'
#define BTM_BYPASS_EXTRA_ACL_SETUP BtmBypassExtraAclSetup()
>                                   ^
> 1 error generated.
17:21:59 ninja failed with: exit status 1
> 
> #### failed to build some targets (05:02:24 (hh:mm:ss)) ####

**Comment by AndyCGYan** [comment]
Happens because LOS updates their FOD implementation quite often. I update monthly following LOS patch merge (scheduled for this weekend) so you can wait for that; alternatively, try resolving the conflict (plus other conflicts in PHH patches) yourself.

**Comment by robpower** [comment]
Thanks for the feedback!

**Comment by AndyCGYan** [comment]
Changes pushed, closing issue.
