### ISSUE TITLE
Use CalyxOS's microG patch to enhance security

### ISSUE THREAD

**Issue by Fei1Yang** [AndyCGYan/treble_build_los#4]
Currently, the [microG patch](https://github.com/AndyCGYan/treble_build_los/blob/lineage-17.1/patches/0001-core-Add-support-for-MicroG.patch) is a serious security issue, if a user mistakenly allows a malicious application to use the `android.permission.FAKE_PACKAGE_SIGNATURE` permission, the app can pretend to be a legitimate app using this package name.

To make it less bad, replace the current patch with [CalyxOS's patch](https://gitlab.com/CalyxOS/platform_frameworks_base/-/commit/dccce9d969f11c1739d19855ade9ccfbacf8ef76.patch) would solve part of the issue:
- It only allows `com.google.android.gms` and `com.android.vending` to fake the signature.
- It uses a predefined signature and ignore the signature provided by the app completely.

**Comment by AndyCGYan** [comment]
Sounds reasonable, not sure whether that'd be overly restrictive and block some legit usecases though. I'll try stuffing it into the October builds to gauge impact.

**Comment by fwg-cag** [comment]
I also would consider this a overly restrictive, blocking some legit use cases. To enhance security, FAKE_SIGNATURE permission might be limited to privileged system apps only:
`TMPF=$(mktemp)`
`sed 's/android:protectionLevel="dangerous"/android:protectionLevel="signature|privileged"/' $BL/patches/0001-core-Add-support-for-MicroG.patch > $TMPF`
`git am $TMPF`
`rm -f $TMPF`

**Comment by Fei1Yang** [comment]
I don't think it's "overly restrictive", beacuse I don't see this permission being used in projects other than microG, If you do find ANY projects that use this permission, then I'll accept the "overly restrictive" term.

If you only want to use it as a test feature, I think you should use riru/xposed modules to opt-in to it rather than making it a built-in feature of the ROM.

**Comment by AndyCGYan** [comment]
October build has been up for 3 days and no complaints so far, however I'm not sure whether there's enough MicroG users here, so I won't close the issue for now.
@Fei1Yang Are you an active MG user, and if yes, have you tried this build yourself?

**Comment by Fei1Yang** [comment]
I'm a microg user, but I don't have an extra phone to test this patch right now (I'm currently using the FakeGApps xposed module with another ROM), I'll test it in about a week and I'll close the issue now, if I find something wrong afterwards, I will report it to you via Telegram.
