### ISSUE TITLE
Note on 0001-Allow-selective-signature-spoofing-for-microG.patch

### ISSUE THREAD

**Issue by fwg-cag** [AndyCGYan/treble_build_los#5]
Andy, the Android sources of services/core/java/com/android/server/pm/PackageManagerService.java have changed. You may run into trouble applying 0001-Allow-selective-signature-spoofing-for-microG.patch at:
@@ -4185,8 +4190,9 @@ public class PackageManagerService extends IPackageManager.Stub
             final Set<String> permissions = ArrayUtils.isEmpty(p.requestedPermissions)
                     ? Collections.emptySet() : permissionsState.getPermissions(userId);

Please check ...

**Comment by waltercool** [comment]
Did you tried with latest commit?

**Comment by AndyCGYan** [comment]
Updated for November a few days ago, should be good. It's easy to correct on your side anyway (3-way apply).
